### ISSUE TITLE
NU1701 when adding build task to .NETStandard 2.0 project

### ISSUE THREAD

**Issue by carstencodes** [dspace-group/dscom#103]
**Description**

Adding the package dSPACE.Runtime.InteropServices.BuildTasks package (added in #102) to projects targetting .NET Standard 2.0 causes NuGet restore to issue a NU1701 warning. 
This is due to the fact, that no group for .NET Standard 2.0 is created in the resulting NuGet package.

Accepted workaround is currently, that the package must be added with ItemMetadata `NoWarn="1702"`.

**Severity**

Major

(.NET Standard 2.0 is losing ground, Workaround exists)

**How to reproduce**

Add the build task to a project targeting .NET Standard 2.0. Run the restore. 

**Acceptance criteria**

The NU1701 warning must not appear.

**Comment by marklechtermann** [comment]
.NET Standard is not in focus of this project any more. Closed
