### ISSUE TITLE
Sorting tests and adding missing test cases in the unit tests 

### ISSUE THREAD

**Issue by SOsterbrink** [dspace-group/dscom#122]
Because there is no clear naming schema, it's sometimes hard to see which test cases are missing. 
Here we should define an easier to read naming schema and rename the tests accordingly.  

There are currently test cases missing in the unit tests. For example: 
- Methods with valid out parameters and valid return values (This likely created problems in #121 ) 

It's likely that we will identify additional missing test cases during the renaming operation.

**Comment by marklechtermann** [comment]
This issue should generally be addressed during refactoring.
