### ISSUE TITLE
The DsComTlbExportTlbReferences and DsComTlbExportAssemblyPaths options are ignored

### ISSUE THREAD

**Issue by marklechtermann** [dspace-group/dscom#128]
I worked out the logic for using the `TypeLibConverter` by using the sink's `ResolveRef` to mirror the argument line commands for the command-line tools. However, I did want to use the build task instead of running code. The documentation implies that the equivalent should be:

```
<DsComTlbExportTlbReferences>C:\Program Files\Common Files\DESIGNER\MSADDNDR.OLB</DsComTlbExportTlbReferences>
```

As a property in my `.csproj`. However, it does not appear that it get passed as an input to the command line tool during the build. I tried with `DsComTlbExportAssemblyPaths` but got the same result; no changes to the command line generated by the build task. 

In both cases, the error is as following:
```
The command "C:\Users\User\.nuget\packages\dspace.runtime.interopservices.buildtasks\0.18.0\build\..\tools\x64\dscom.exe      tlbexport    C:\GitHub\Rubberduck\Rubberduck.Main\bin\Debug\net48\Rubberduck.dll --out C:\GitHub\Rubberduck\Rubberduck.Main\bin\Debug\net48\\Rubberduck.tlb" exited with code 1.
```
with additional warnings:
```
TX00000000	Type library exporter encountered an error while processing 'Microsoft.VisualStudio.Interop'. Error: Could not load file or assembly 'Microsoft.VisualStudio.Imaging.Interop.14.0.DesignTime, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
TX00000000	Type library exporter encountered an error while processing 'Rubberduck'. Error: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
```

I should note that in the `TypeLibConverter` + sink's `ResolveRef` approach, I basically check if it's trying to resolve the `Microsoft.VisualStudio.Interop` in which case I pass back `C:\Program Files\Common Files\DESIGNER\MSADDNDR.OLB` which has the needed type information without all the junk. This works correctly but not sure how to replicate this as a build task.

_Originally posted by @bclothier in https://github.com/dspace-group/dscom/issues/120#issuecomment-1400103114_

**Comment by carstencodes** [comment]
@bclothier @marklechtermann 

The `DsComTlbExportTlbReferences` should be defined as [ItemGroup](https://learn.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild?view=vs-2022). 

Hence the correct usage is 

```xml
<ItemGroup>
<DsComTlbExportTlbReferences Include="C:\Program Files\Common Files\DESIGNER\MSADDNDR.OLB" />
</ItemGroup>
```

**Comment by bclothier** [comment]
Thanks for the guidance.

Going back to the original example from the linked issue, this would work and not yield any warnings:

```
dscom.exe tlbexport .\Rubberduck.Deployment\bin\Rubberduck.dll --out .\Rubberduck.Deployment\bin\Test.tlb --asmpath 'C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089' --tlbreference 'C:\Program Files (x86)\Common Files\Designer\MSADDNDR.dll' --verbose
```

Therefore, I used the following in the `.csproj`:

```
<ItemGroup>
  <PackageReference Include="dSPACE.Runtime.InteropServices.BuildTasks" Version="0.17.0" NoWarn="NU1701">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
  </PackageReference>
  <DsComTlbExportAssemblyPaths Include="C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089" />
  <DsComTlbExportTlbReferences Include="C:\Program Files\Common Files\DESIGNER\MSADDNDR.OLB" />
</ItemGroup>
```

This appears to replicate the result from the command line and yields no warning.

**Comment by carstencodes** [comment]
Ok, I'll update the documentation then,
