### ISSUE TITLE
ComAliasNameAttribute unsupported

### ISSUE THREAD

**Issue by carstencodes** [dspace-group/dscom#132]
The .NET Runtime offers the ability to map datatypes using the [ComAliasNameAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.comaliasnameattribute?view=net-7.0).

This is currently unsupported by dscom. 

Contributions welcome

**Comment by bclothier** [comment]
Just to note - this is only used during import, not export. I do not think `tlbexp.exe` nor `regasm.exe` will actually use it; it is only decorated by the `tblimp.exe` for generating a PIA. 

[You can see it's listed under the heading of conversion tools](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/apply-interop-attributes#conversion-tool-attributes) with the following paragraph:

> The following table describes attributes that COM interop tools apply during the conversion process. You do not apply these attributes at design time.

The [attributes in listed in the first table above](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/apply-interop-attributes#design-time-attributes) would be used during the type library export.

**Comment by carstencodes** [comment]
Oh, I thought it was for export as well. Closing the issue.
