### ISSUE TITLE
Build task fails

### ISSUE THREAD

**Issue by EO3-Kopf** [dspace-group/dscom#138]
After adding the nuget package to my project the build returns an error:

> Fehler	MSB4113	Die angegebene Bedingung @(DsComTlbAliasNames->Count() > 0) wird zu @(DsComTlbAliasNames->Count() > 0) statt zu einem booleschen Wert ausgewertet.

According to the message the error originates in `dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets`, line 47. It seems there is a typo in the condition phrase of `_DsComAliasNames`  (comparing it to the surrounding ones). I assume it should be `Condition="@(DsComTlbAliasNames->Count()) &gt; 0"` instead of `Condition="@(DsComTlbAliasNames->Count() &gt; 0)"` (wrong position of the closing paranthesis).

**Comment by carstencodes** [comment]
I won't manage to watch for this today. I'll come back to you next week.
