### ISSUE TITLE
Overriding library name during build task

### ISSUE THREAD

**Issue by EO3-Kopf** [dspace-group/dscom#147]
This is an idea for enhancement:

If I got it right, `dscom` picks `AssemblyName` as name of the library in the TLB. Maybe in some cases it might come in handy to override this behaviour and define a name manually.

Therefore I suggest adding a new item which the build task consumes also. Something like `DsComTlbLibraryName`

**Comment by carstencodes** [comment]
According to the documentation, this would be `_DsComExportTypeLibraryTargetFile`.

Since it is part of the targets file and not of the props file, it cannot be overridden at the moment.

I've never thought, that this might be an urgent case. 

I'll try to fix it later that day.

**Comment by EO3-Kopf** [comment]
To my understanding `_DsComExportTypeLibraryTargetFile` is not what I am talking about. According to [README](https://github.com/dspace-group/dscom#parameters) this defines the resulting file name. I am talking about the library name _inside_ the .tlb-file. The name behind the `library`-statement in [IDL](https://learn.microsoft.com/en-us/windows/win32/midl/library).

**Comment by EO3-Kopf** [comment]
By the way, it is _not_ urgent. Just a thought about (future) enhancement.

**Comment by carstencodes** [comment]
Ok, this is far beyond my expertise ...

**Comment by SOsterbrink** [comment]
I'll look into it and try to find a solution when I have some time for it later today.

**Comment by carstencodes** [comment]
I'll add some options to the build tasks for the pull request within the next days.
