### ISSUE TITLE
Code Style check fails after .NET update in github actions 

### ISSUE THREAD

**Issue by SOsterbrink** [dspace-group/dscom#158]
The code style check fails after the used windows image was updated: 

**Worked with:** 
https://github.com/dspace-group/dscom/actions/runs/4281683514/jobs/7455010898

> Current runner version: '2.301.1'
> Operating System
>   Microsoft Windows Server 2022
>   10.0.20348
>   Datacenter
> Runner Image
>   Image: windows-2022
>   Version: **20230219.1**
>   Included Software: https://github.com/actions/runner-images/blob/win22/20230219.1/images/win/Windows2022-Readme.md
>   Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230219.1

**Failing with:**
https://github.com/dspace-group/dscom/actions/runs/4363953151/jobs/7630677977 

> Current runner version: '2.302.1'
> Operating System
>   Microsoft Windows Server 2022
>   10.0.20348
>   Datacenter
> Runner Image
>   Image: windows-2022
>   Version: **20230226.1**
>   Included Software: https://github.com/actions/runner-images/blob/win22/20230226.1/images/win/Windows2022-Readme.md
>   Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230226.1

**Comment by marklechtermann** [comment]
It looks like this is more likely due to the nuget updates.
The Main Branch compiles and the UnitTest runs

https://github.com/dspace-group/dscom/actions/runs/4365722510

Something has changed with the new version of Microsoft.Build.Utilities.Core

**Comment by SOsterbrink** [comment]
The code style check fails even for the main branch: 

https://github.com/dspace-group/dscom/actions/runs/4372666280/

**Comment by carstencodes** [comment]
Fixed with https://github.com/dspace-group/dscom/pull/157/commits/2eda1a676326602ad4adcbdb023e03007bf10fde in #157

**Comment by SOsterbrink** [comment]
The problem is also relevant in the release action
