### ISSUE TITLE
FileLoadException during tlbexport

### ISSUE THREAD

**Issue by mlessmann** [dspace-group/dscom#168]
dscom tlbexport may throw a FileLoadException when trying to load a dependent assembly if that assembly was previously loaded from a different path. This has occured for the WindowsBase.dll assembly, which is part of the .NET Windows Runtime.

The issue may be fixed by using Assembly.LoadFile() rather than Assembly.LoadFrom() when loading dependent assemblies from paths specified by --asmpath.

**Comment by mlessmann** [comment]
The root of the issue seems to be that WindowsBase.dll exists in 2 places:
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.16
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.16

Projects with <UseWPF>true</UseWPF> reference the latter assembly, all other projects the former.

**Comment by marklechtermann** [comment]
The problem with LoadFile is that no fusion (no LoadFrom Context) is used - which is what is intended. 
So with .NET Fullframework we have the problem that we would have to reimplement the loading mechanism to load assemblies from the GAC.

Have you been able to find a workaround for your problem?
