### ISSUE TITLE
Option to bypass imported types

### ISSUE THREAD

**Issue by ProSimPC** [dspace-group/dscom#173]
Hello,
First of all, many thanks for this extremely useful tool. We use it on many projects and it saves us a lot of time.
I'd like to suggest a small improvement, unless the functionality already exists but I've missed it: our assemblies contain imported interop types and, from time to time, these imported types appear several times in the hierarchy when the tlb is exported. This generates a TYPE_E_DUPLICATEID error when the SetGuid method is called, preventing the command from executing correctly.
It seems to me that it would be fairly easy to get around this problem by adding an option (e.g. --includeimportedtypes) and a test on type.IsImport in the LibraryWriter.CollectAllTypes method so that imported types can be ignored.
What do you think?

**Comment by marklechtermann** [comment]
Hello ProSimPC,

first of all sorry for the late feedback. Nice that this project could help you.
Can you provide us a demo project on GitHub for your problem that shows this error.

Beste Grüße, Mark

**Comment by marklechtermann** [comment]
If there is no more need, then I close this issue.
You are welcome to open the issue again
