### ISSUE TITLE
Check compatibility with .NET 8 

### ISSUE THREAD

**Issue by SOsterbrink** [dspace-group/dscom#196]
We need to check how .NET 8 compatibility can be achieved and how .NET 8 will affect our tool. 

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8

**Comment by gureedo** [comment]
I faced strange error.
dscom fails to export tlb if assembly references System.Security.Cryptography.
 `Interop+BCrypt+BCRYPT_DSA_KEY_BLOB_V2+<Count>e__FixedBuffer, System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`
I think it's related to .NET 8.

**Comment by SOsterbrink** [comment]
Thank you for the example. I'll include it in some of my tests. 

The current dscom version is not yet built with .NET 8. It's likely that most interactions with System libraries from .NET 8 will create errors.

**Comment by SOsterbrink** [comment]
> I faced strange error. dscom fails to export tlb if assembly references System.Security.Cryptography. `Interop+BCrypt+BCRYPT_DSA_KEY_BLOB_V2+<Count>e__FixedBuffer, System.Security.Cryptography, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a` I think it's related to .NET 8.

The dscom problem is rooted in the fact that for some reason `System.Security.Cryptography` does not have a namespace. 
And we expect that every library has a namespace.

**Comment by SOsterbrink** [comment]
The behavior in connection with the System.Security.Cryptography library is moved into a separate issue, because it's not a general  problem with .NET 8
