### ISSUE TITLE
Error: Could not load file or assembly 'PresentationFramework' on tlbexport

### ISSUE THREAD

**Issue by mgaffigan** [dspace-group/dscom#204]
When using dscom to export a library referencing WPF or another unavailable library, exceptions are thrown from `ComAliasNameResolver`.  We don't really want to "fix" those reference problems, just to have `tlbexport` ignore them.  `LibraryWriter` already has the logic to turn missing references into warnings, but `ComAliasNameWriter` is missing them.

Related to #120, PR incoming

**Comment by SOsterbrink** [comment]
@mgaffigan : I started a new Release v1.4.0 so that you can use your fix. It should take a few minutes until it's available.

**Comment by mgaffigan** [comment]
Thanks for the quick merge, and for making dscom open. It’s a great benefit to the community.
