### ISSUE TITLE
ComAliasNameResolver can't report problems because the logging sink was not yet created. 

### ISSUE THREAD

**Issue by SOsterbrink** [dspace-group/dscom#206]
In #205 we have a problems that exceptions can't be properly logged as warnings because the `LoggingTypeLibExporterSink` has not been created yet. 

Ideas to solve this: 

- We will have to move some of the functions from the constructors of the `INameResolvers` to an initialization method which is called after the Logging sink was created.

**Comment by marklechtermann** [comment]
There is currently no need
