### ISSUE TITLE
Export TLB is drilling too deep in Assembly.

### ISSUE THREAD

**Issue by PaulStSmith** [dspace-group/dscom#241]
If you have a .NET COM library that references an COM Interop assembly, and try to export the TLB of your library, the exporter tries to export the interop assembly into the TLB.

For example, I have a .NET COM library that makes reference to an Interop with Excel and the TLB export fails because it tries to export the Excel interop and some GUID in the interop are the same, then it fails when trying to assign the GUID to a member or class.

**Comment by SOsterbrink** [comment]
Hi, 
I'll try to take a closer look at your issue later, but it's likely that I will be a few days before I can get back to you because I have a some very busy days in the next days.  
Maybe someone of the others here can help you faster.

**Comment by PaulStSmith** [comment]
Thanks for the reply.
If you guys need the assembly I'm working with, let me know.

**Comment by marklechtermann** [comment]
You could try to generate the tlb with the option "--createmissingdependenttlbs false".
In this case dscom will not create any dependent tlb's.

`dscom tlbexport yourassembly.dll --createmissingdependenttlbs false`

**Comment by marklechtermann** [comment]
@PaulStSmith 
Does this help you and can we close the issue?
