### ISSUE TITLE
DsComTypeLibraryEmbedAfterBuild and _DsComExportTypeLibraryAssemblyFile

### ISSUE THREAD

**Issue by electro-logic** [dspace-group/dscom#286]
Hi,
I'm trying the new EmbedTypeLibrary feature that sounds very promising.

My project has a BaseOutputPath to a custom directory and so I have in my project

>    < BaseOutputPath>D:\</BaseOutputPath>
>    < _DsComExportTypeLibraryAssemblyFile>$(BaseOutputPath)</_DsComExportTypeLibraryAssemblyFile>

The problem is that dscom.exe is called with the right --tlbexport, but the wrong --embed parameter, pointing to the default OutputPath.

`dscom.exe tlbexport "D:\x86\Release\net6.0\MyLibrary.dll" --embed C:\...\obj\x86\Release\net6.0\MyLibrary.comhost.dll --out "D:\x86\Release\net6.0\MyLibrary.tlb"" exited with code 1.`

**Comment by marklechtermann** [comment]
@bclothier can you take a look at this?

**Comment by bclothier** [comment]
As I understand it, at this stage of the build, the `.comhost.dll` hasn't been yet copied to the output. That is why we use Microsoft's msbuild variable to get to the intermediate path:

https://github.com/dspace-group/dscom/blob/f997cefc2b5944be732e0429b98ba9953ce65678/src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets#L56

Can you confirm that the file is present in the `obj` folder? If so, can you further verify that there is no errors embedding type library into the `.comhost.dll` by running the command manually.

**Comment by bclothier** [comment]
Hmm, the thing is that dscom does not control the building of the `*.comhost.dll`; this is done by Microsoft during the build. All dscom does is embedding the type library into the built `*.comhost.dll` which as I mentioned is located in the `obj` folder at that stage but at the end of the build, it should be then copied into the output directory, which is again done by Microsoft and not by dscom. 

This does not explain why you would get exit code of 1. Do you see any detailed error in your build output log?

**Comment by electro-logic** [comment]
Seems that I need to compile two times in row to get the .tlb embedded, can this be fixed?

**Comment by carstencodes** [comment]
ComHostIntermediatePath is created in _CreateComHost in [Microsoft.NET.Sdk.targets](https://github.com/dotnet/sdk/blob/aaee17ef7954216c7d62f9ec4b60d51f126f7306/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.targets#L797).

This is part of `CompileDependsOn`. `CompileDependsOn` must be executed before `Compile`. 
`Compile` is part of `CoreBuildDependsOn`, which is executed before `CoreBuild`, which itself is part of `BuildDependsOn`.

`DsComExportTypeLibraryAfterBuild` is executed after [`AfterBuild`](https://github.com/dspace-group/dscom/blob/f997cefc2b5944be732e0429b98ba9953ce65678/src/dscom.build/dSPACE.Runtime.InteropServices.BuildTasks.Tools.targets#L33).

So, in theory, the ComHostIntermediatePath must exist.

Unfortunately _CreateComHost depends on CoreCompile, which it itself is a dependency to.

So, if I see this correctly, building twice here is desired by .NET SDK ...

**Comment by electro-logic** [comment]
I agree with closing this issue, but I think would be better to document this behavior somewhere
