### ISSUE TITLE
[Bug] Can't resolve dependencies when using C++/CLI Assemblies

### ISSUE THREAD

**Issue by electro-logic** [dspace-group/dscom#292]
When launching

`dscom tlbexport my.dll --asmpath D:\mypath`

I found an unhandled exception with Visual Visual Studio:

`Exception thrown at 0x00007FFB7531831A in dscom.exe: Microsoft C++ exception: HRMsgException at memory location 0x00000000001C7380.`

at the function LoadFromAssemblyPath(dllToLoad) 

https://github.com/dspace-group/dscom/blob/14dad8d8c1fd75d996e00b2d2af949a9c2623cc5/src/dscom.client/AssemblyResolver.cs#L48

and the issue is that not all types are loaded.

By replacing LoadFromAssemblyPath() with

`Assembly.LoadFile(dllToLoad)`

the assembly and all dependencies are correctly loaded.

Additional details:

my.dll is defining a COM interface and a class derived from MyLib.MyClass that is a class in another assembly that actually implement the interface

```
    [ComVisible(true)]
    [InterfaceType(ComInterfaceType.InterfaceIsDual)]
    [Guid("AA3C9EF2-AAAA-424B-8A96-35910B102956")]
    public interface ISum
    {
        int Sum(int a, int b);
    }

    [ComVisible(true)]
    [ClassInterface(ClassInterfaceType.None)]
    [Guid("AAAB3576-AAAA-4652-A87A-3579DD85AF69")]
    public class ComSum : MyLib.MyClass, ISum
    {
        
    }
```

**Comment by electro-logic** [comment]
All .dll are located in the same D:\mypath folder.
dllToLoad is pointing to the right file when calling LoadFromAssemblyPath(), but for some reasons seems the wrong API to call.
I haven't deeply investigate, but for some reason Assembly.LoadFile() is working.

**Comment by electro-logic** [comment]
MyLib (that contains MyClass) is a C++/CLI .DLL
The issue is related to https://github.com/dotnet/sdk/issues/44168

**Comment by carstencodes** [comment]
Ah, ok. Is this a .NET 6/7/8/9 DLL assembly or is it a dotnet fullframework C++/CLI DLL? Which dependencies are involved, i.e. C++ DLLs next to the assembly?

If so, we just "forgot" to attach the [DllImportResolver](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.nativelibrary.setdllimportresolver?view=net-8.0#system-runtime-interopservices-nativelibrary-setdllimportresolver(system-reflection-assembly-system-runtime-interopservices-dllimportresolver))

**Comment by carstencodes** [comment]
Is it any special or can you provide me the input assemblies?

**Comment by electro-logic** [comment]
Here a demo (both projects .NET 9) to reproduce the issue:

[BugDemo.zip](https://github.com/user-attachments/files/17803246/BugDemo.zip)

dscom (non patched) is emitting a warning

dscom : warning TX00000000 : Type library exporter encountered an error while processing 'CsLibrary'. Error: Could not load file or assembly 'CppLibrary, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

and the resulting .tlb file is missing the type.
C++/CLI is actually making CLR assemblies as output (same as C#), so I'm not sure DllImportResolver is the issue.

**Comment by carstencodes** [comment]
Ok, here we seem to have found an issue:

With C++/CLI Images, we might have another issue found in AssemblyLoadContext:

```Cannot load a mixed assembly into a collectible AssemblyLoadContext. The format of the file 'C:\temp\dscom292\BugDemo\CsLibrary\bin\Debug\net9.0-windows\CppLibrary.dll' is invalid.
```

This is currently limited by the [dotnet runtime itself](https://github.com/dotnet/runtime/issues/72237).

I'll check back with @marklechtermann @matthiasnissen and @SOsterbrink what the original issue was why the assembly load context was chosen to be collectible.

**Comment by carstencodes** [comment]
Ok, we're digging a bit deeper currently.

@SOsterbrink went through the history of the AssemblyResolver:

- @mlessmann has introduced the assembly load context without any further description in #192 
- @SOsterbrink has made the assemblyloadcontext unloadable in #209 for #207 - With special purpose to support mixedmode assemblies again

We will dig deeper into this. 

@marklechtermann I would like to use the BugDemo by @electro-logic as an additional quality gate in order not to mess this up again.

**Comment by SOsterbrink** [comment]
@carstencodes  Good idea about the additional quality gate. 
I am slightly confused why my commit message said I prevented unloading and my commit code allows it. I think my brain was confused by "unloadable" as in removable form the context and "unloadable" as in can't be loaded and I somehow switched the boolean values by accident.

**Comment by SOsterbrink** [comment]
It came back in https://github.com/dspace-group/dscom/pull/278/commits/d568f88c6a1ceca82dc63838f82d826f4fbad7ca 
and at least according to the commit messages, it was intentional. 

 I don't know why, but maybe @bclothier  could answer that.

**Comment by carstencodes** [comment]
@SOsterbrink I think I have a solution in ac80673a24a3275ffd22964a70ee7faaa51758f4.

A cleaner way would be to check the PE headers before loading the assemblies. If the assembly has C++/CLI mixedmode settings, we should load them into the defaultcontext.
If the library shall be used as embed-Target, we should raise an error.

cc @marklechtermann

**Comment by electro-logic** [comment]
I also suggest to "promote" the warning to an error, just in case

`dscom : warning TX00000000 : Type library exporter encountered an error while processing 'CsLibrary'. Error: Could not load file or assembly 'CppLibrary, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.`

**Comment by electro-logic** [comment]
Thanks all for the fix, works like a charm!
