### ISSUE TITLE
Property Setter do not use INVOKEKIND.INVOKE_PROPERTYPUTREF

### ISSUE THREAD

**Issue by mavToday** [dspace-group/dscom#306]
Hello,

we want to use dscom32 to register our Assemblies for an old VB6 Application, after migrating to .NET 8.0 from .NET 4.8.

I found here in Issue while exporting Properties with our exported Types.

This is one of the exported Classes:
```
<ComVisible(True)>
<Guid("...")>
<ClassInterface(ClassInterfaceType.None)>
<ComDefaultInterface(GetType(ISomeClassInterop))>
Public Class SomeClass

End Class
```

This is the exported Interface with the Property
```
<ComVisible(True)>
<Guid("...")>
<InterfaceType(ComInterfaceType.InterfaceIsDual)>
Public Interface ISomeOtherInterface

  Property Some As SomeClass

End Interface
```

After exporting the Assembly as a *.tlb i found out, that the property is exported with INVOKEKIND.INVOKE_PROPERTYPUT. With .NET 4.8 i was exported with INVOKEKIND.INVOKE_PROPERTYPUTREF.

My problem is now, that i could not implement the Interface 'ISomeOtherInterface' in VB6, because of the setter. I temporarly fixed the issue with the given code in 'PropertySetMethodWriter.Create':

```
public override void Create()
{
    try
    {
        if (MethodInfo.GetParameters().Any(p =>
         {
             var type = p.ParameterType;
 
             // Object is not 'IsClass'
             if (type == typeof(object))
                 return true;
 
             // every class except special ones (e.g. String)
             // are handles as references
             if (type.IsClass && !type.IsSpecialHandledClass())
                 return true;
 
             // interfaces are same as classes
             if (type.IsInterface)
                 return true;
 
             return false;
         }))
        {
            InvokeKind = INVOKEKIND.INVOKE_PROPERTYPUTREF;
        }
    }
    catch (FileNotFoundException)
    {
        //FileNotFoundException can occur on GetParameters() method, disable method writer
    }
 
    base.Create();
}
```

I'm not sure, if this is the absolutely correct fix, therefore i open this issue.

best regards
Patrick

**Comment by marklechtermann** [comment]
I can confirm that this is a bug!
In this case this should be an INVOKE_PROPERTYPUTREF.
We would be happy to receive a PullRequest 😃

In the case of C#, this can be verified with this 

```csharp
using System.Runtime.InteropServices;

namespace tmp;

[ComVisible(true)]
[InterfaceType(ComInterfaceType.InterfaceIsDual)]
public interface ISomeOtherInterface
{
    SomeClass Some { get; set; }
}


[ComVisible(true)]
[ClassInterface(ClassInterfaceType.None)]
[ComDefaultInterface(typeof(ISomeOtherInterface))]
public class SomeClass : ISomeOtherInterface
{
    public SomeClass Some { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
}
```

Result of dscom:

```yaml
  - name: Some
    memberId: 1610743808
    docString: 
    callConv: CC_STDCALL
    kind: FUNC_DISPATCH
    invokeKind: INVOKE_PROPERTYPUT
```

Result of tlbexp:

```yaml
  - name: Some
    memberId: 1610743808
    docString: 
    callConv: CC_STDCALL
    kind: FUNC_DISPATCH
    invokeKind: INVOKE_PROPERTYPUTREF
```

...and we should add a new unit test for this scenario to:
[https://github.com/dspace-group/dscom/blob/main/src/dscom.test/tests/PropertyTest.cs](https://github.com/dspace-group/dscom/blob/main/src/dscom.test/tests/PropertyTest.cs)
