### ISSUE TITLE
New property overrides do not work as intended

### ISSUE THREAD

**Issue by Arakys7** [dspace-group/dscom#309]
In PR #294, I added the `DsComExportTypeLibraryTargetFile` and `DsComExportTypeLibraryAssemblyFile` msbuild properties to override the default values defined by `_DsComExportTypeLibraryTargetFile` and `_DsComExportTypeLibraryAssemblyFile`

However, I did not implement them well, and they don't work.
For example:
If a user sets `DsComExportTypeLibraryTargetFile` to a value, `_DsComExportTypeLibraryTargetFile` does not use it.

**Comment by carstencodes** [comment]
Hi,

I will take a look at this on monday, if this is ok for you.

**Comment by Arakys7** [comment]
Hi, I'm working on a PR for this (better to fix my own mistake)
I just wanted to document the problem before creating a PR.

**Comment by carstencodes** [comment]
Closed by #311 

Will create a release in the course of the week
