### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by tinohager** [dspace-group/dscom#47]
Hi. i have create a small test project and try your project but it thow an error, can you help me please?

> PS C:\Users\user1\Documents\GitHub\TestComExport\TestComExport\bin\x86\Debug\net6.0> dscom tlbexport .\TestComExport.dll
Failed to export type library. Could not load file or assembly 'TestComExport, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableComHosting>true</EnableComHosting>
    <Platforms>x86</Platforms>
  </PropertyGroup>

</Project>
```

```cs
using System.Runtime.InteropServices;

namespace TestComExport
{
    [ComVisible(true), Guid("FA63E193-BF1E-41A2-95B6-D0AEDC825CFB")]
    [InterfaceType(ComInterfaceType.InterfaceIsIDispatch)]
    public interface IFlyNumbers
    {
        [DispId(1)]
        int GetDay();

        [DispId(2)]
        int GetMonth();

        [DispId(3)]
        int GetYear();

        [DispId(4)]
        int DayOfYear();
    }

    [ComVisible(true), Guid("F9AFBEBF-401F-4074-BEA8-9C49FF3EA1EB")]
    [ClassInterface(ClassInterfaceType.None)]
    [ProgId("FlyTest")]
    public class FlyNumbers : IFlyNumbers
    {
        public FlyNumbers() { }

        public int GetDay()
        {
            return DateTime.Today.Day;
        }

        public int GetMonth()
        {
            return DateTime.Today.Month;
        }

        public int GetYear()
        {
            return DateTime.Today.Year;
        }

        public int DayOfYear()
        {
            return DateTime.Now.DayOfYear;
        }
    }
}
```

**Comment by marklechtermann** [comment]
Hallo Tino,

unfortunately we only support **x64** assemblies.
With the following change it should work:

```
<PlatformTarget>x64</PlatformTarget>
``` 

I have just added this limitation to the README.md.
Thanks for your feedback!

**Comment by marklechtermann** [comment]
#48 Only 64 Bit support (x64)

**Comment by tinohager** [comment]
Do you happen to know if the tlb from an x64 dll also works together with an x86 dll?

**Comment by marklechtermann** [comment]
As far as I know, you cannot use a 64 TLB for a 32 bit COM DLL.
The problem is that when the TLB is created, the `SYSKIND` in the `TYPELIBATTR` is specified. 
In case of a `dscom` generated TBL this is `SYSKIND.SYS_WIN64`.

Furthermore, dscom is a 64 bit executable, so no x86 assembly can be loaded (only "Any" would work).

**Comment by tinohager** [comment]
Thanks for the reply. I think we try now with x64 and `dll Surrogate`

**Comment by marklechtermann** [comment]
Hallo @tinohager,

32Bit assemblies are now supported!
Take a look at the documentation, everything is explained there ;-)

**Comment by tinohager** [comment]
Thanks, I'm on vacation right now and will look at it as soon as I get back to the office, thanks
