### ISSUE TITLE
Support for 32Bit assemblies

### ISSUE THREAD

**Issue by SOsterbrink** [dspace-group/dscom#60]
Currently it is a known limitation that only 64 bit libraries are supported. As shown by #58  and #47 there is a demand for 32 bit libraries to be supported. 

It must be evaluated if the changes from #58 will be sufficient and if further changes are required.

**Comment by SOsterbrink** [comment]
Until now it was considered a limitation an no further effort was planned. If an easy fix can be found it should be implemented. 
The solution proposed in #58 will not be sufficient because it would require two separate dotnet tools. 
As such our command line tool would at least require a new command line parameter to switch the bitness to 32 bit.

**Comment by Delucion** [comment]
I want to add in the request for 32 bit support. It is a critical issue for a professional project I'm working on, and right now I'm considering manually dismantling the .tlb file and figuring out how to make it compatible for 32 bit that way. It would be much preferred if this could be automated. Thank you to all those working on this, it's a much-needed solution in most ways, but this last critical issue is standing in the way for my project.

**Comment by marklechtermann** [comment]
32Bit assemblie are now supported!
If you have an "AnyCPU" assembly, then you can create a 32Bit TLB with the switch "--win32".

If your assembly is a 32bit assembly, then the "dscom32.exe" must be used.
This can be downloaded from the release page.

[](https://github.com/dspace-group/dscom/releases)

**Comment by Delucion** [comment]
awesome!! thank you so much!
