### ISSUE TITLE
IntPtr is mapped to Int64 in TLBs generated by dscom32

### ISSUE THREAD

**Issue by ericcdub** [dspace-group/dscom#83]
Hi there,

I'm attempting to export TLBs from a 32-bit .NET class library which contains several interfaces and classes.
Some of the methods defined in these interfaces require IntPtr arguments, and when I import the TLB into unmanaged C++, the resulting .TLH requires int64 * arguments in place of the IntPtr ones, when I would've expected them to require long *.

I've verified the contents of the TLB using OleView, so it would seem that dscom32 is not differentiating IntPtr into long* and int64*.
I'm wondering is this expected behaviour or a bug?

**Comment by marklechtermann** [comment]
Hi @ericcdub,

it's a bug!
Regarding Microsoft documentation:
[https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0)

> The [IntPtr](https://learn.microsoft.com/en-us/dotnet/api/system.intptr?view=net-6.0) type is designed to be an integer whose size is the same as a pointer. That is, an instance of this type is expected to be 32 bits in a 32-bit process and 64 bits in a 64-bit process.

In case of a 32-bit assembly the correct type should be `VT_I4`

**Comment by marklechtermann** [comment]
Fixed in release v0.16.1

[https://github.com/dspace-group/dscom/releases/latest](https://github.com/dspace-group/dscom/releases/latest)

**Comment by ericcdub** [comment]
Great stuff, thanks for the rapid fix 👍
